// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MovieAPI.Entity;
using System;

namespace MovieAPI.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20180718061013_MovieAPI.Entity.MovieDbContext")]
    partial class MovieAPIEntityMovieDbContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieAPI.Entity.MovieList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Comments");

                    b.Property<string>("Original_title");

                    b.Property<double>("Popularity");

                    b.Property<string>("Poster_path");

                    b.Property<string>("Release_date");

                    b.Property<string>("Title");

                    b.Property<double>("Vote_average");

                    b.Property<int>("Vote_count");

                    b.Property<bool>("WatchList");

                    b.Property<string>("overview");

                    b.HasKey("Id");

                    b.ToTable("MovieList");
                });
#pragma warning restore 612, 618
        }
    }
}
